### ISSUE TITLE
Album art pulling from source other than file

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#2]
Love the app, have been looking for replacements for SpotMenu. That said —

It looks like this app pulls album art from some internet source rather than the file? For example, when I play a live/concert version of a song in my Music library, rather than displaying the embedded album art it's displaying the album art for the studio/album version of the song. Is it possible to display the embedded art?

**Comment by nbolar** [comment]
Hey there! Thanks, funnily enough I made this app because SpotMenu strangely stopped working for me.

Yes, you are correct, I'm using the iTunes Search API to get info about the current playing song and as you've experienced it can be slightly unreliable with the artwork. The initial versions of the app did actually use the embedded artwork but it was **very inefficient** and so I decided to go with using the API instead. And so I don't see that changing any time soon, sorry about that.

**Comment by nbolar** [comment]
So I just pushed v1.7.1 where I made a change to the way the artwork was being pulled. If you're running this version, I'd like to know if it's now showing the correct artwork or whether it's still incorrect? Thanks!

**Comment by dscos** [comment]
Sorry I didn't respond sooner, was traveling. I am on 1.7.2 now and my Music tracks that are live versions with embedded album art just showing no artwork at all now in PlayStatus, if that answers your question.

**Comment by nbolar** [comment]
Okay that's strange. Does it not show any artwork at all for any song or is it just the live versions? Do you mind sharing the name/link of one such song? It'll probably help in debugging to some extent.

**Comment by dscos** [comment]
For background, here's my use case — I've switched back and forth between Spotify and Apple Music, right now I'm using Spotify for streaming most commercially released music, but I use the Music app a lot both for locally stored music I have that is not available on Spotify as well as live music.

So for example, I have the Joanna Newsom album "The Milk-Eyed Mender" in Music because it not available on Spotify. This album is in the mp3 format and PlayStatus displays album art just fine.

![Screen Shot 2020-03-09 at 11 28 37 PM](https://user-images.githubusercontent.com/14156552/76282606-c2543300-625d-11ea-9ea1-659acee45e64.jpg)

I also have a lot of live music by the band Bon Iver, most but not all of which is in the Apple Lossless/ALAC m4a format. So for example, a live version of the song "Heavenly Father" by Bon Iver shows no album art in PlayStatus.

![Screen Shot 2020-03-09 at 11 29 55 PM](https://user-images.githubusercontent.com/14156552/76282752-43132f00-625e-11ea-89ed-1840f17f59c8.jpg)

Hope that information helps.

**Comment by nbolar** [comment]
This helps a lot! Thank you for this. So right off the bat I know why it isn't showing the artwork, it's because that particular music catalog is not in the database that the iTunes API uses. I can now see why you'd prefer the embedded artwork itself because many a time iTunes won't have that version of the song in their database. Okay with that being said, I think I'll add back in the original functionality of pulling the embedded artwork first before fetching it from the iTunes API. Just give me a couple of days to work on it and I'll update this thread once again when an update to the app has been pushed. Thank you once again!

**Comment by nbolar** [comment]
I managed to get it up and running quicker than I thought so a new version, 1.8, has just been pushed. Let me know if this fixes the issue.

**Comment by dscos** [comment]
Indeed it has. Awesome. If you add a donate option to the app or this Github page, I'll throw you a few bucks for your work to address my nitpicking lol!

**Comment by nbolar** [comment]
Haha thank you, but this project began as a hobby and the fact that there are people like you who take the time and effort in helping make this app better is more than I could ask for. So thank you once again for downloading this app.
