### ISSUE TITLE
PlayStatus crashes when clicked on while playing a local file via Spotify

### ISSUE THREAD

**Issue by Ein-Tim** [nbolar/PlayStatus#23]
PlayStatus crashes under macOS Monterey 12.1 on a MacBook Air 2020 (M1), when a local file is listened on Spotify. 

Before crashing, it correctly shows the name of the track in the status bar, however, as soon as I click on it, it crashes.

**Comment by nbolar** [comment]
@Ein-Tim Thanks for your feedback. I will work on fixing this for the next release.

**Comment by nbolar** [comment]
Sorry for the long wait. I have updated the app. It no longer crashes. However due to the limitation of Spotify's AppleScript API, I'm unable to pull local files' artwork from it. So I'm using the iTunes API to grab the artwork. Since that API is not always accurate, in case it can't pull the artwork, it just shows a default artwork .

**Comment by Ein-Tim** [comment]
I have update to https://github.com/nbolar/PlayStatus/releases/tag/v2.3 and can confirm that this works now! Thank you @nbolar!
