### ISSUE TITLE
Does not work without Spotify installed

### ISSUE THREAD

**Issue by mikemcduffie** [nbolar/PlayStatus#27]
I'm running macOS 12.6.1 on a 2022 MBP

App description says it supports Apple Music (I assume this is the app and not the just the service but Apple is terrible at naming of late) and iTunes (again suggests the app supports local music playback).

App shows"No Music Playing" while playing music in the macOS Music app and when the clicked repeatedly opens a dialog box to find Spotify (which I do not have installed or any interest in). 

Am I missing something?

**Comment by nbolar** [comment]
Hmmm that is very strange. When you get the pop up, what happens when you choose "Music" (the Apple Music app)?

PlayStatus supports the Music app as well as iTunes and Spotify. It does by extension support local music playback.

This sounds like an edge case I didn't anticipate correctly while developing the app. Apologies for that. But I believe if you choose "Music" when that pop-up shows, it should work correctly.

**Comment by mikemcduffie** [comment]
Thanks. That worked. But I must say it never occurred to me to select another media player app when the dialog specifically asked for "Spotify". I assumed it would proceed to ask for another supported app after canceling the Spotify dialog or just support the known system default Music app. May I suggest modifying the dialog to make it clearer?

**Comment by nbolar** [comment]
Fixed as of version 2.5.
